// ============================================================
// FOREMOST PET FOODS - SEED DATA
// Realistic sample data for development & demonstration
// ============================================================

import { Product, Customer, Employee, Order, Promotion, Supplier, GiftCard, LoyaltyTransaction } from './types';
import { v4 as uuidv4 } from 'uuid';

// ---- PRODUCTS ----
export const SEED_PRODUCTS: Product[] = [
  // ===== DOG FOOD =====
  {
    id: 'prod-001',
    name: 'Fromm Gold Adult Dog Food',
    slug: 'fromm-gold-adult-dog',
    description: 'Fromm Gold Adult is a premium dry dog food crafted with duck, chicken, and lamb as the primary protein sources. Formulated with probiotics and a balanced blend of vitamins and minerals for optimal health.',
    shortDescription: 'Premium duck, chicken & lamb formula for adult dogs',
    brand: 'Fromm Family Foods',
    category: 'food',
    subcategory: 'dry-food',
    petType: ['dog'],
    images: ['/products/fromm-gold-adult.jpg'],
    price: 79.99,
    compareAtPrice: 89.99,
    costPrice: 52.00,
    sku: 'FRM-GLD-ADT-15',
    barcode: '072705105151',
    weight: 15,
    weightUnit: 'kg',
    inventory: {
      productId: 'prod-001',
      quantity: 24,
      reorderPoint: 6,
      reorderQuantity: 18,
      location: 'Aisle 1A',
      lastRestocked: '2026-03-10',
      supplier: 'sup-fromm',
      status: 'in-stock',
    },
    tags: ['premium', 'all-breed', 'best-seller', 'autoship-eligible'],
    isActive: true,
    isFeatured: true,
    isAutoShipEligible: true,
    lifestage: ['adult'],
    breedSize: ['all-sizes'],
    ingredients: 'Duck, Chicken Meal, Chicken, Oatmeal, Pearled Barley, Brown Rice, White Rice...',
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2026-03-10T00:00:00Z',
  },
  {
    id: 'prod-002',
    name: 'GO! Solutions Carnivore Chicken, Turkey + Duck',
    slug: 'go-carnivore-chicken-turkey-duck',
    description: 'A protein-packed recipe featuring premium chicken, turkey, and duck. Grain-free formula with probiotics for digestive health. Perfect for active dogs who thrive on a high-protein diet.',
    shortDescription: 'High-protein grain-free blend for active dogs',
    brand: 'GO! Solutions',
    category: 'food',
    subcategory: 'dry-food',
    petType: ['dog'],
    images: ['/products/go-carnivore-dog.jpg'],
    price: 74.99,
    costPrice: 48.00,
    sku: 'GO-CARN-CTD-12',
    barcode: '815260003001',
    weight: 10,
    weightUnit: 'kg',
    inventory: {
      productId: 'prod-002',
      quantity: 18,
      reorderPoint: 5,
      reorderQuantity: 15,
      location: 'Aisle 1B',
      lastRestocked: '2026-03-08',
      supplier: 'sup-petcurean',
      status: 'in-stock',
    },
    tags: ['grain-free', 'high-protein', 'best-seller', 'autoship-eligible'],
    isActive: true,
    isFeatured: true,
    isAutoShipEligible: true,
    lifestage: ['adult'],
    breedSize: ['all-sizes'],
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2026-03-08T00:00:00Z',
  },
  {
    id: 'prod-003',
    name: 'Fromm Heartland Gold Puppy Food',
    slug: 'fromm-heartland-gold-puppy',
    description: 'Grain-free puppy formula with red meat proteins including beef, pork, and lamb. Enriched with DHA for brain development and calcium for strong bones.',
    shortDescription: 'Grain-free red meat formula for growing puppies',
    brand: 'Fromm Family Foods',
    category: 'food',
    subcategory: 'dry-food',
    petType: ['dog'],
    images: ['/products/fromm-heartland-puppy.jpg'],
    price: 84.99,
    costPrice: 55.00,
    sku: 'FRM-HRT-PUP-12',
    weight: 12,
    weightUnit: 'kg',
    inventory: {
      productId: 'prod-003',
      quantity: 12,
      reorderPoint: 4,
      reorderQuantity: 12,
      location: 'Aisle 1A',
      lastRestocked: '2026-03-05',
      supplier: 'sup-fromm',
      status: 'in-stock',
    },
    tags: ['puppy', 'grain-free', 'premium', 'autoship-eligible'],
    isActive: true,
    isFeatured: false,
    isAutoShipEligible: true,
    lifestage: ['puppy'],
    breedSize: ['all-sizes'],
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2026-03-05T00:00:00Z',
  },
  {
    id: 'prod-004',
    name: 'ACANA Highest Protein Meadowland',
    slug: 'acana-highest-protein-meadowland',
    description: 'Biologically appropriate dog food featuring free-run chicken, turkey, and cage-free eggs. Made with fresh regional ingredients in award-winning kitchens.',
    shortDescription: 'Biologically appropriate with free-run poultry',
    brand: 'ACANA',
    category: 'food',
    subcategory: 'dry-food',
    petType: ['dog'],
    images: ['/products/acana-meadowland.jpg'],
    price: 89.99,
    costPrice: 58.00,
    sku: 'ACN-HP-MDL-11',
    weight: 11.4,
    weightUnit: 'kg',
    inventory: {
      productId: 'prod-004',
      quantity: 15,
      reorderPoint: 4,
      reorderQuantity: 12,
      location: 'Aisle 1C',
      lastRestocked: '2026-03-07',
      supplier: 'sup-champion',
      status: 'in-stock',
    },
    tags: ['premium', 'high-protein', 'grain-free', 'autoship-eligible'],
    isActive: true,
    isFeatured: true,
    isAutoShipEligible: true,
    lifestage: ['adult'],
    breedSize: ['all-sizes'],
    createdAt: '2025-01-20T00:00:00Z',
    updatedAt: '2026-03-07T00:00:00Z',
  },
  // ===== DOG TREATS =====
  {
    id: 'prod-005',
    name: 'GREENIES Original Dental Treats - Regular',
    slug: 'greenies-dental-regular',
    description: 'Vet-recommended dental treats that clean teeth, freshen breath, and maintain healthy gums. The unique texture and shape clean down to the gumline.',
    shortDescription: 'Vet-recommended dental chews for fresh breath',
    brand: 'GREENIES',
    category: 'treats',
    subcategory: 'dental-treats',
    petType: ['dog'],
    images: ['/products/greenies-regular.jpg'],
    price: 34.99,
    costPrice: 21.00,
    sku: 'GRN-DT-REG-27',
    weight: 765,
    weightUnit: 'g',
    inventory: {
      productId: 'prod-005',
      quantity: 30,
      reorderPoint: 8,
      reorderQuantity: 24,
      location: 'Aisle 2A',
      lastRestocked: '2026-03-09',
      supplier: 'sup-mars',
      status: 'in-stock',
    },
    tags: ['dental', 'best-seller', 'vet-recommended'],
    isActive: true,
    isFeatured: false,
    isAutoShipEligible: true,
    lifestage: ['adult'],
    breedSize: ['medium', 'large'],
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2026-03-09T00:00:00Z',
  },
  {
    id: 'prod-006',
    name: 'Fromm Tenderollies Chick-a-Rollie',
    slug: 'fromm-tenderollies-chicken',
    description: 'Soft and tender meat treats made with real chicken. Perfect for training or as a delicious reward. No artificial colors or flavors.',
    shortDescription: 'Soft chicken meat treats for training & rewards',
    brand: 'Fromm Family Foods',
    category: 'treats',
    subcategory: 'soft-treats',
    petType: ['dog'],
    images: ['/products/fromm-tenderollies.jpg'],
    price: 12.99,
    costPrice: 7.50,
    sku: 'FRM-TEND-CHK-8',
    weight: 226,
    weightUnit: 'g',
    inventory: {
      productId: 'prod-006',
      quantity: 45,
      reorderPoint: 10,
      reorderQuantity: 30,
      location: 'Aisle 2A',
      lastRestocked: '2026-03-10',
      supplier: 'sup-fromm',
      status: 'in-stock',
    },
    tags: ['training', 'soft-treat', 'no-artificial'],
    isActive: true,
    isFeatured: false,
    isAutoShipEligible: false,
    lifestage: ['all-stages'],
    breedSize: ['all-sizes'],
    createdAt: '2025-03-01T00:00:00Z',
    updatedAt: '2026-03-10T00:00:00Z',
  },
  // ===== DOG TOYS =====
  {
    id: 'prod-007',
    name: 'KONG Classic Dog Toy - Large',
    slug: 'kong-classic-large',
    description: 'The gold standard of dog toys. Ultra-durable natural rubber with an unpredictable bounce that keeps dogs engaged. Stuff with treats for hours of enrichment.',
    shortDescription: 'Ultra-durable rubber toy for hours of enrichment',
    brand: 'KONG',
    category: 'toys',
    subcategory: 'chew-toys',
    petType: ['dog'],
    images: ['/products/kong-classic.jpg'],
    price: 18.99,
    costPrice: 10.50,
    sku: 'KNG-CLS-LG',
    weight: 350,
    weightUnit: 'g',
    inventory: {
      productId: 'prod-007',
      quantity: 20,
      reorderPoint: 5,
      reorderQuantity: 15,
      location: 'Aisle 3A',
      lastRestocked: '2026-03-06',
      supplier: 'sup-kong',
      status: 'in-stock',
    },
    tags: ['durable', 'enrichment', 'best-seller', 'vet-recommended'],
    isActive: true,
    isFeatured: true,
    isAutoShipEligible: false,
    lifestage: ['adult'],
    breedSize: ['large', 'giant'],
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2026-03-06T00:00:00Z',
  },
  // ===== CAT FOOD =====
  {
    id: 'prod-008',
    name: 'GO! Solutions Carnivore Chicken, Turkey + Duck Cat',
    slug: 'go-carnivore-cat',
    description: 'Premium grain-free recipe packed with protein from chicken, turkey, and duck. Formulated with taurine for heart health and omega oils for a lustrous coat.',
    shortDescription: 'Grain-free high-protein formula for cats',
    brand: 'GO! Solutions',
    category: 'food',
    subcategory: 'dry-food',
    petType: ['cat'],
    images: ['/products/go-carnivore-cat.jpg'],
    price: 54.99,
    costPrice: 35.00,
    sku: 'GO-CARN-CAT-7',
    weight: 7.3,
    weightUnit: 'kg',
    inventory: {
      productId: 'prod-008',
      quantity: 16,
      reorderPoint: 4,
      reorderQuantity: 12,
      location: 'Aisle 4A',
      lastRestocked: '2026-03-08',
      supplier: 'sup-petcurean',
      status: 'in-stock',
    },
    tags: ['grain-free', 'high-protein', 'best-seller', 'autoship-eligible'],
    isActive: true,
    isFeatured: true,
    isAutoShipEligible: true,
    lifestage: ['adult'],
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2026-03-08T00:00:00Z',
  },
  {
    id: 'prod-009',
    name: 'Fromm Gold Adult Cat Food',
    slug: 'fromm-gold-adult-cat',
    description: 'A balanced and nutritious dry cat food made with duck, chicken, and salmon. Enhanced with probiotics, taurine, and a complete vitamin profile.',
    shortDescription: 'Premium duck, chicken & salmon blend for cats',
    brand: 'Fromm Family Foods',
    category: 'food',
    subcategory: 'dry-food',
    petType: ['cat'],
    images: ['/products/fromm-gold-cat.jpg'],
    price: 49.99,
    costPrice: 32.00,
    sku: 'FRM-GLD-CAT-5',
    weight: 4.5,
    weightUnit: 'kg',
    inventory: {
      productId: 'prod-009',
      quantity: 14,
      reorderPoint: 4,
      reorderQuantity: 10,
      location: 'Aisle 4A',
      lastRestocked: '2026-03-10',
      supplier: 'sup-fromm',
      status: 'in-stock',
    },
    tags: ['premium', 'best-seller', 'autoship-eligible'],
    isActive: true,
    isFeatured: false,
    isAutoShipEligible: true,
    lifestage: ['adult'],
    createdAt: '2025-01-20T00:00:00Z',
    updatedAt: '2026-03-10T00:00:00Z',
  },
  {
    id: 'prod-010',
    name: 'ORIJEN Cat & Kitten',
    slug: 'orijen-cat-kitten',
    description: 'Biologically appropriate food inspired by the variety of fresh meats that cats are evolved to eat. Made with 85% quality animal ingredients.',
    shortDescription: 'Biologically appropriate with 85% meat content',
    brand: 'ORIJEN',
    category: 'food',
    subcategory: 'dry-food',
    petType: ['cat'],
    images: ['/products/orijen-cat.jpg'],
    price: 64.99,
    costPrice: 42.00,
    sku: 'ORJ-CK-5',
    weight: 5.4,
    weightUnit: 'kg',
    inventory: {
      productId: 'prod-010',
      quantity: 10,
      reorderPoint: 3,
      reorderQuantity: 10,
      location: 'Aisle 4B',
      lastRestocked: '2026-03-07',
      supplier: 'sup-champion',
      status: 'in-stock',
    },
    tags: ['premium', 'high-protein', 'grain-free', 'autoship-eligible'],
    isActive: true,
    isFeatured: true,
    isAutoShipEligible: true,
    lifestage: ['kitten', 'adult'],
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2026-03-07T00:00:00Z',
  },
  // ===== CAT TREATS =====
  {
    id: 'prod-011',
    name: 'GREENIES Feline Dental Treats - Catnip Flavor',
    slug: 'greenies-feline-dental-catnip',
    description: 'Crunchy dental treats that clean teeth and freshen breath with a taste cats love. Made with natural ingredients and added vitamins.',
    shortDescription: 'Crunchy dental treats cats love',
    brand: 'GREENIES',
    category: 'treats',
    subcategory: 'dental-treats',
    petType: ['cat'],
    images: ['/products/greenies-cat.jpg'],
    price: 8.99,
    costPrice: 5.00,
    sku: 'GRN-FDT-CP-60',
    weight: 60,
    weightUnit: 'g',
    inventory: {
      productId: 'prod-011',
      quantity: 35,
      reorderPoint: 8,
      reorderQuantity: 24,
      location: 'Aisle 5A',
      lastRestocked: '2026-03-09',
      supplier: 'sup-mars',
      status: 'in-stock',
    },
    tags: ['dental', 'catnip', 'vet-recommended'],
    isActive: true,
    isFeatured: false,
    isAutoShipEligible: false,
    lifestage: ['adult'],
    createdAt: '2025-03-01T00:00:00Z',
    updatedAt: '2026-03-09T00:00:00Z',
  },
  // ===== DOG ACCESSORIES =====
  {
    id: 'prod-012',
    name: 'Premium Nylon Adjustable Collar',
    slug: 'premium-nylon-collar',
    description: 'Durable nylon collar with stainless steel D-ring and quick-release buckle. Available in multiple colors. Reflective stitching for night visibility.',
    shortDescription: 'Durable nylon collar with reflective stitching',
    brand: 'Foremost Essentials',
    category: 'collars-leashes',
    subcategory: 'collars',
    petType: ['dog'],
    images: ['/products/nylon-collar.jpg'],
    price: 16.99,
    costPrice: 8.00,
    sku: 'FE-COL-NYL-M',
    weight: 85,
    weightUnit: 'g',
    inventory: {
      productId: 'prod-012',
      quantity: 40,
      reorderPoint: 10,
      reorderQuantity: 30,
      location: 'Aisle 6A',
      lastRestocked: '2026-03-04',
      supplier: 'sup-generic',
      status: 'in-stock',
    },
    tags: ['durable', 'reflective', 'adjustable'],
    isActive: true,
    isFeatured: false,
    isAutoShipEligible: false,
    lifestage: ['adult'],
    breedSize: ['medium'],
    createdAt: '2025-04-01T00:00:00Z',
    updatedAt: '2026-03-04T00:00:00Z',
  },
  // ===== CAT TOYS =====
  {
    id: 'prod-013',
    name: 'Interactive Feather Wand Toy',
    slug: 'interactive-feather-wand',
    description: 'Engaging feather wand toy with telescoping handle and interchangeable feather attachments. Encourages exercise and natural hunting instincts.',
    shortDescription: 'Telescoping feather wand for active play',
    brand: 'Foremost Essentials',
    category: 'toys',
    subcategory: 'interactive-toys',
    petType: ['cat'],
    images: ['/products/feather-wand.jpg'],
    price: 11.99,
    costPrice: 4.50,
    sku: 'FE-TOY-FW-01',
    weight: 120,
    weightUnit: 'g',
    inventory: {
      productId: 'prod-013',
      quantity: 25,
      reorderPoint: 6,
      reorderQuantity: 20,
      location: 'Aisle 5B',
      lastRestocked: '2026-03-06',
      supplier: 'sup-generic',
      status: 'in-stock',
    },
    tags: ['interactive', 'feather', 'exercise'],
    isActive: true,
    isFeatured: false,
    isAutoShipEligible: false,
    lifestage: ['all-stages'],
    createdAt: '2025-05-01T00:00:00Z',
    updatedAt: '2026-03-06T00:00:00Z',
  },
  // ===== HEALTH & WELLNESS =====
  {
    id: 'prod-014',
    name: 'Salmon Oil Skin & Coat Supplement',
    slug: 'salmon-oil-supplement',
    description: 'Pure wild Alaskan salmon oil rich in Omega-3 and Omega-6 fatty acids. Promotes healthy skin, lustrous coat, joint health, and immune support for dogs and cats.',
    shortDescription: 'Omega-rich oil for skin, coat & joint health',
    brand: 'Wellness',
    category: 'health',
    subcategory: 'supplements',
    petType: ['dog', 'cat'],
    images: ['/products/salmon-oil.jpg'],
    price: 24.99,
    costPrice: 14.00,
    sku: 'WEL-SO-16',
    weight: 473,
    weightUnit: 'g',
    inventory: {
      productId: 'prod-014',
      quantity: 18,
      reorderPoint: 5,
      reorderQuantity: 15,
      location: 'Aisle 7A',
      lastRestocked: '2026-03-08',
      supplier: 'sup-wellness',
      status: 'in-stock',
    },
    tags: ['supplement', 'omega', 'skin-coat', 'joint-health'],
    isActive: true,
    isFeatured: false,
    isAutoShipEligible: true,
    lifestage: ['all-stages'],
    breedSize: ['all-sizes'],
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2026-03-08T00:00:00Z',
  },
  // ===== GROOMING =====
  {
    id: 'prod-015',
    name: 'Professional Deshedding Tool',
    slug: 'deshedding-tool',
    description: 'Stainless steel deshedding edge reaches through topcoat to safely remove loose undercoat and reduce shedding up to 90%. Ergonomic handle with anti-slip grip.',
    shortDescription: 'Reduces shedding up to 90% with gentle action',
    brand: 'Foremost Essentials',
    category: 'grooming',
    subcategory: 'brushes-combs',
    petType: ['dog', 'cat'],
    images: ['/products/deshedding-tool.jpg'],
    price: 29.99,
    costPrice: 15.00,
    sku: 'FE-GRM-DSH-M',
    weight: 200,
    weightUnit: 'g',
    inventory: {
      productId: 'prod-015',
      quantity: 12,
      reorderPoint: 3,
      reorderQuantity: 10,
      location: 'Aisle 7B',
      lastRestocked: '2026-03-05',
      supplier: 'sup-generic',
      status: 'in-stock',
    },
    tags: ['grooming', 'deshedding', 'professional'],
    isActive: true,
    isFeatured: false,
    isAutoShipEligible: false,
    lifestage: ['adult'],
    breedSize: ['medium', 'large'],
    createdAt: '2025-06-01T00:00:00Z',
    updatedAt: '2026-03-05T00:00:00Z',
  },
  // ===== BEDS =====
  {
    id: 'prod-016',
    name: 'Orthopedic Memory Foam Dog Bed - Large',
    slug: 'orthopedic-dog-bed-large',
    description: 'Premium orthopedic bed with 4-inch memory foam base. Waterproof liner with removable, machine-washable cover. Ideal for senior dogs or dogs with joint issues.',
    shortDescription: 'Premium memory foam bed for joint support',
    brand: 'Foremost Essentials',
    category: 'beds-furniture',
    subcategory: 'orthopedic-beds',
    petType: ['dog'],
    images: ['/products/ortho-bed.jpg'],
    price: 89.99,
    costPrice: 45.00,
    sku: 'FE-BED-MF-LG',
    weight: 5,
    weightUnit: 'kg',
    dimensions: { length: 110, width: 80, height: 15 },
    inventory: {
      productId: 'prod-016',
      quantity: 8,
      reorderPoint: 2,
      reorderQuantity: 6,
      location: 'Aisle 8A',
      lastRestocked: '2026-03-03',
      supplier: 'sup-generic',
      status: 'in-stock',
    },
    tags: ['orthopedic', 'memory-foam', 'senior', 'washable'],
    isActive: true,
    isFeatured: true,
    isAutoShipEligible: false,
    lifestage: ['adult', 'senior'],
    breedSize: ['large', 'giant'],
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2026-03-03T00:00:00Z',
  },
  // ===== FISH / AQUARIUM (Second Line Location) =====
  {
    id: 'prod-017',
    name: 'Tropical Fish Flake Food',
    slug: 'tropical-fish-flakes',
    description: 'Premium flake food formulated for all tropical freshwater fish. Enhanced with vitamins and minerals for vibrant color and optimal health.',
    shortDescription: 'Color-enhancing flakes for tropical fish',
    brand: 'Foremost Essentials',
    category: 'food',
    subcategory: 'fish-food',
    petType: ['fish'],
    images: ['/products/fish-flakes.jpg'],
    price: 9.99,
    costPrice: 4.50,
    sku: 'FE-FF-TRP-100',
    weight: 100,
    weightUnit: 'g',
    inventory: {
      productId: 'prod-017',
      quantity: 22,
      reorderPoint: 5,
      reorderQuantity: 15,
      location: 'Aquatics Section',
      lastRestocked: '2026-03-07',
      supplier: 'sup-aquatics',
      status: 'in-stock',
    },
    tags: ['tropical', 'color-enhancing', 'flake-food'],
    isActive: true,
    isFeatured: false,
    isAutoShipEligible: false,
    lifestage: ['all-stages'],
    createdAt: '2025-04-01T00:00:00Z',
    updatedAt: '2026-03-07T00:00:00Z',
  },
  {
    id: 'prod-018',
    name: 'Aquarium Water Conditioner 500mL',
    slug: 'aquarium-water-conditioner',
    description: 'Instantly makes tap water safe for fish by neutralizing chlorine, chloramines, and heavy metals. Also provides a synthetic slime coating to protect fish.',
    shortDescription: 'Makes tap water safe for all freshwater fish',
    brand: 'Foremost Essentials',
    category: 'aquarium',
    subcategory: 'water-care',
    petType: ['fish'],
    images: ['/products/water-conditioner.jpg'],
    price: 14.99,
    costPrice: 7.00,
    sku: 'FE-AQ-WC-500',
    weight: 500,
    weightUnit: 'g',
    inventory: {
      productId: 'prod-018',
      quantity: 15,
      reorderPoint: 4,
      reorderQuantity: 12,
      location: 'Aquatics Section',
      lastRestocked: '2026-03-07',
      supplier: 'sup-aquatics',
      status: 'in-stock',
    },
    tags: ['water-care', 'dechlorinator', 'essential'],
    isActive: true,
    isFeatured: false,
    isAutoShipEligible: false,
    lifestage: ['all-stages'],
    createdAt: '2025-04-01T00:00:00Z',
    updatedAt: '2026-03-07T00:00:00Z',
  },
  // ===== SENIOR DOG FOOD =====
  {
    id: 'prod-019',
    name: 'NOW FRESH Senior Dog Recipe',
    slug: 'now-fresh-senior-dog',
    description: '100% fresh turkey, salmon, and duck formula designed for senior dogs. Grain-free with added glucosamine and chondroitin for joint support.',
    shortDescription: 'Fresh turkey & salmon recipe for senior dogs',
    brand: 'NOW FRESH',
    category: 'food',
    subcategory: 'dry-food',
    petType: ['dog'],
    images: ['/products/now-fresh-senior.jpg'],
    price: 72.99,
    costPrice: 47.00,
    sku: 'NOW-SR-DOG-11',
    weight: 11.4,
    weightUnit: 'kg',
    inventory: {
      productId: 'prod-019',
      quantity: 10,
      reorderPoint: 3,
      reorderQuantity: 10,
      location: 'Aisle 1D',
      lastRestocked: '2026-03-06',
      supplier: 'sup-petcurean',
      status: 'in-stock',
    },
    tags: ['senior', 'grain-free', 'joint-support', 'autoship-eligible'],
    isActive: true,
    isFeatured: false,
    isAutoShipEligible: true,
    lifestage: ['senior'],
    breedSize: ['all-sizes'],
    createdAt: '2025-02-15T00:00:00Z',
    updatedAt: '2026-03-06T00:00:00Z',
  },
  {
    id: 'prod-020',
    name: 'Stainless Steel Double Bowl Feeder',
    slug: 'stainless-steel-double-bowl',
    description: 'Premium stainless steel double bowl feeder with non-slip silicone base. Dishwasher safe, rust-resistant, and sized for medium to large dogs.',
    shortDescription: 'Non-slip stainless steel double bowl set',
    brand: 'Foremost Essentials',
    category: 'bowls-feeders',
    subcategory: 'bowls',
    petType: ['dog'],
    images: ['/products/double-bowl.jpg'],
    price: 22.99,
    costPrice: 10.00,
    sku: 'FE-BWL-SS-DBL',
    weight: 800,
    weightUnit: 'g',
    inventory: {
      productId: 'prod-020',
      quantity: 15,
      reorderPoint: 4,
      reorderQuantity: 12,
      location: 'Aisle 6B',
      lastRestocked: '2026-03-05',
      supplier: 'sup-generic',
      status: 'in-stock',
    },
    tags: ['stainless-steel', 'non-slip', 'dishwasher-safe'],
    isActive: true,
    isFeatured: false,
    isAutoShipEligible: false,
    lifestage: ['all-stages'],
    breedSize: ['medium', 'large'],
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2026-03-05T00:00:00Z',
  },
];

// ---- CUSTOMERS ----
export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cust-001',
    email: 'sarah.mitchell@email.com',
    phone: '(705) 555-0101',
    firstName: 'Sarah',
    lastName: 'Mitchell',
    address: {
      street: '42 Queen St E',
      city: 'Sault Ste. Marie',
      province: 'ON',
      postalCode: 'P6A 1Y5',
      country: 'CA',
    },
    pets: [
      {
        id: 'pet-001',
        name: 'Luna',
        type: 'dog',
        breed: 'Golden Retriever',
        birthDate: '2022-06-15',
        weight: 29,
        weightUnit: 'kg',
        allergies: ['chicken'],
        dietaryNeeds: ['grain-free'],
        medications: [],
        preferredFood: ['prod-004'],
        notes: 'Loves the ACANA Meadowland',
      },
      {
        id: 'pet-002',
        name: 'Mochi',
        type: 'cat',
        breed: 'Ragdoll',
        birthDate: '2023-03-20',
        weight: 5,
        weightUnit: 'kg',
        allergies: [],
        dietaryNeeds: [],
        medications: [],
        preferredFood: ['prod-010'],
        notes: 'Very picky eater',
      },
    ],
    loyaltyTier: 'gold-paw',
    loyaltyPoints: 12450,
    totalSpent: 3245.67,
    totalOrders: 48,
    joinDate: '2024-01-15',
    lastVisit: '2026-03-12',
    preferences: {
      emailNotifications: true,
      smsNotifications: true,
      autoShipReminders: true,
      birthdayReminders: true,
      communicationLanguage: 'en',
    },
    autoShipSubscriptions: [
      {
        id: 'as-001',
        customerId: 'cust-001',
        productId: 'prod-004',
        productName: 'ACANA Highest Protein Meadowland',
        quantity: 1,
        frequencyDays: 30,
        nextDeliveryDate: '2026-03-28',
        lastDeliveryDate: '2026-02-28',
        price: 89.99,
        discount: 10,
        status: 'active',
        createdAt: '2025-06-01T00:00:00Z',
      },
    ],
    giftCards: [],
    notes: 'Loyal customer since opening. Always shops for both Luna and Mochi.',
    tags: ['vip', 'autoship', 'multi-pet'],
    isActive: true,
  },
  {
    id: 'cust-002',
    email: 'mike.thompson@email.com',
    phone: '(705) 555-0202',
    firstName: 'Mike',
    lastName: 'Thompson',
    address: {
      street: '88 Northern Ave',
      city: 'Sault Ste. Marie',
      province: 'ON',
      postalCode: 'P6B 4J1',
      country: 'CA',
    },
    pets: [
      {
        id: 'pet-003',
        name: 'Bear',
        type: 'dog',
        breed: 'Bernese Mountain Dog',
        birthDate: '2021-11-03',
        weight: 45,
        weightUnit: 'kg',
        allergies: [],
        dietaryNeeds: ['large-breed'],
        medications: ['joint supplement'],
        preferredFood: ['prod-001'],
        notes: 'On Fromm Gold, loves the Tenderollies treats',
      },
    ],
    loyaltyTier: 'diamond-paw',
    loyaltyPoints: 28900,
    totalSpent: 7820.45,
    totalOrders: 96,
    joinDate: '2023-09-01',
    lastVisit: '2026-03-13',
    preferences: {
      emailNotifications: true,
      smsNotifications: false,
      autoShipReminders: true,
      birthdayReminders: true,
      communicationLanguage: 'en',
    },
    autoShipSubscriptions: [
      {
        id: 'as-002',
        customerId: 'cust-002',
        productId: 'prod-001',
        productName: 'Fromm Gold Adult Dog Food',
        quantity: 1,
        frequencyDays: 21,
        nextDeliveryDate: '2026-03-25',
        lastDeliveryDate: '2026-03-04',
        price: 79.99,
        discount: 15,
        status: 'active',
        createdAt: '2024-01-15T00:00:00Z',
      },
    ],
    giftCards: [],
    notes: 'Top customer. Bear is a big boy — goes through food fast!',
    tags: ['vip', 'diamond', 'autoship', 'high-value'],
    isActive: true,
  },
  {
    id: 'cust-003',
    email: 'jenny.chen@email.com',
    phone: '(705) 555-0303',
    firstName: 'Jenny',
    lastName: 'Chen',
    address: {
      street: '215 Bay St',
      city: 'Sault Ste. Marie',
      province: 'ON',
      postalCode: 'P6A 1X2',
      country: 'CA',
    },
    pets: [
      {
        id: 'pet-004',
        name: 'Whiskers',
        type: 'cat',
        breed: 'Domestic Shorthair',
        birthDate: '2020-08-12',
        weight: 4.5,
        weightUnit: 'kg',
        allergies: [],
        dietaryNeeds: [],
        medications: [],
        preferredFood: ['prod-009'],
        notes: 'Strictly Fromm Gold cat food',
      },
      {
        id: 'pet-005',
        name: 'Noodle',
        type: 'cat',
        breed: 'Siamese',
        birthDate: '2023-12-01',
        weight: 3.8,
        weightUnit: 'kg',
        allergies: ['beef'],
        dietaryNeeds: [],
        medications: [],
        preferredFood: ['prod-008'],
        notes: 'Younger cat, on GO! Solutions',
      },
    ],
    loyaltyTier: 'silver-paw',
    loyaltyPoints: 4200,
    totalSpent: 890.30,
    totalOrders: 22,
    joinDate: '2025-03-10',
    lastVisit: '2026-03-11',
    preferences: {
      emailNotifications: true,
      smsNotifications: true,
      autoShipReminders: false,
      birthdayReminders: true,
      communicationLanguage: 'en',
    },
    autoShipSubscriptions: [],
    giftCards: [{ giftCardId: 'gc-001', code: 'FPF-GIFT-2026A', balance: 25.00 }],
    notes: 'Two cat household. Very knowledgeable about cat nutrition.',
    tags: ['cat-parent', 'multi-pet'],
    isActive: true,
  },
  {
    id: 'cust-004',
    email: 'david.larose@email.com',
    phone: '(705) 555-0404',
    firstName: 'David',
    lastName: 'LaRose',
    pets: [
      {
        id: 'pet-006',
        name: 'Duke',
        type: 'dog',
        breed: 'German Shepherd',
        birthDate: '2019-04-22',
        weight: 38,
        weightUnit: 'kg',
        allergies: [],
        dietaryNeeds: ['high-protein'],
        medications: [],
        preferredFood: ['prod-002'],
        notes: 'Active working dog, needs high protein',
      },
    ],
    loyaltyTier: 'paw',
    loyaltyPoints: 1500,
    totalSpent: 320.00,
    totalOrders: 8,
    joinDate: '2025-11-01',
    lastVisit: '2026-03-09',
    preferences: {
      emailNotifications: false,
      smsNotifications: false,
      autoShipReminders: false,
      birthdayReminders: false,
      communicationLanguage: 'en',
    },
    autoShipSubscriptions: [],
    giftCards: [],
    notes: 'New customer. Switched from big box store.',
    tags: ['new-customer'],
    isActive: true,
  },
  {
    id: 'cust-005',
    email: 'pat.williams@email.com',
    phone: '(705) 555-0505',
    firstName: 'Patricia',
    lastName: 'Williams',
    address: {
      street: '312 Albert St W',
      city: 'Sault Ste. Marie',
      province: 'ON',
      postalCode: 'P6A 3K9',
      country: 'CA',
    },
    pets: [
      {
        id: 'pet-007',
        name: 'Buddy',
        type: 'dog',
        breed: 'Labrador Retriever',
        birthDate: '2015-02-14',
        weight: 32,
        weightUnit: 'kg',
        allergies: [],
        dietaryNeeds: ['senior', 'joint-support'],
        medications: ['glucosamine'],
        preferredFood: ['prod-019'],
        notes: 'Senior lab, needs joint support food',
      },
    ],
    loyaltyTier: 'gold-paw',
    loyaltyPoints: 9800,
    totalSpent: 2100.00,
    totalOrders: 42,
    joinDate: '2024-05-20',
    lastVisit: '2026-03-12',
    preferences: {
      emailNotifications: true,
      smsNotifications: true,
      autoShipReminders: true,
      birthdayReminders: true,
      communicationLanguage: 'en',
    },
    autoShipSubscriptions: [
      {
        id: 'as-003',
        customerId: 'cust-005',
        productId: 'prod-019',
        productName: 'NOW FRESH Senior Dog Recipe',
        quantity: 1,
        frequencyDays: 28,
        nextDeliveryDate: '2026-03-30',
        lastDeliveryDate: '2026-03-02',
        price: 72.99,
        discount: 10,
        status: 'active',
        createdAt: '2025-01-10T00:00:00Z',
      },
    ],
    giftCards: [],
    notes: 'Has been coming for years. Very attached to Buddy. Always asks about senior supplements.',
    tags: ['loyal', 'autoship', 'senior-pet'],
    isActive: true,
  },
];

// ---- EMPLOYEES ----
export const SEED_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    firstName: 'Owner',
    lastName: 'Admin',
    email: 'admin@foremostpetfoods.ca',
    phone: '(705) 949-2559',
    role: 'owner',
    pin: '1234',
    isActive: true,
    hireDate: '2020-01-01',
    schedule: [],
    permissions: ['all'],
    salesTotal: 0,
    transactionCount: 0,
  },
  {
    id: 'emp-002',
    firstName: 'Jamie',
    lastName: 'Reynolds',
    email: 'jamie@foremostpetfoods.ca',
    phone: '(705) 555-1002',
    role: 'manager',
    pin: '5678',
    isActive: true,
    hireDate: '2022-03-15',
    schedule: [],
    permissions: ['pos', 'inventory', 'customers', 'reports', 'promotions'],
    salesTotal: 145230.50,
    transactionCount: 1842,
  },
  {
    id: 'emp-003',
    firstName: 'Alex',
    lastName: 'Nguyen',
    email: 'alex@foremostpetfoods.ca',
    phone: '(705) 555-1003',
    role: 'cashier',
    pin: '9012',
    isActive: true,
    hireDate: '2024-09-01',
    schedule: [],
    permissions: ['pos', 'customers'],
    salesTotal: 67890.25,
    transactionCount: 956,
  },
  {
    id: 'emp-004',
    firstName: 'Morgan',
    lastName: 'Beaulieu',
    email: 'morgan@foremostpetfoods.ca',
    phone: '(705) 555-1004',
    role: 'associate',
    pin: '3456',
    isActive: true,
    hireDate: '2025-06-15',
    schedule: [],
    permissions: ['pos', 'inventory'],
    salesTotal: 23450.00,
    transactionCount: 412,
  },
];

// ---- GIFT CARDS ----
export const SEED_GIFT_CARDS: GiftCard[] = [
  {
    id: 'gc-001',
    code: 'FPF-GIFT-2026A',
    originalBalance: 50.00,
    currentBalance: 25.00,
    purchasedBy: 'cust-001',
    assignedTo: 'cust-003',
    isActive: true,
    transactions: [
      {
        id: 'gct-001',
        giftCardId: 'gc-001',
        type: 'purchase',
        amount: 50.00,
        balanceAfter: 50.00,
        note: 'Purchased in-store',
        timestamp: '2026-01-15T10:30:00Z',
      },
      {
        id: 'gct-002',
        giftCardId: 'gc-001',
        type: 'redemption',
        amount: -25.00,
        balanceAfter: 25.00,
        orderId: 'ord-sample-1',
        note: 'Used for cat food purchase',
        timestamp: '2026-02-20T14:15:00Z',
      },
    ],
    createdAt: '2026-01-15T10:30:00Z',
  },
  {
    id: 'gc-002',
    code: 'FPF-GIFT-2026B',
    originalBalance: 100.00,
    currentBalance: 100.00,
    purchasedBy: 'cust-002',
    isActive: true,
    transactions: [
      {
        id: 'gct-003',
        giftCardId: 'gc-002',
        type: 'purchase',
        amount: 100.00,
        balanceAfter: 100.00,
        note: 'Birthday gift for friend',
        timestamp: '2026-03-01T11:00:00Z',
      },
    ],
    createdAt: '2026-03-01T11:00:00Z',
  },
  {
    id: 'gc-003',
    code: 'FPF-GIFT-2026C',
    originalBalance: 25.00,
    currentBalance: 0.00,
    purchasedBy: 'cust-005',
    assignedTo: 'cust-004',
    isActive: false,
    transactions: [
      {
        id: 'gct-004',
        giftCardId: 'gc-003',
        type: 'purchase',
        amount: 25.00,
        balanceAfter: 25.00,
        note: 'Holiday promotion card',
        timestamp: '2025-12-20T09:00:00Z',
      },
      {
        id: 'gct-005',
        giftCardId: 'gc-003',
        type: 'redemption',
        amount: -25.00,
        balanceAfter: 0.00,
        orderId: 'ord-sample-2',
        note: 'Full balance used',
        timestamp: '2026-01-05T16:30:00Z',
      },
    ],
    createdAt: '2025-12-20T09:00:00Z',
  },
];

// ---- PROMOTIONS ----
export const SEED_PROMOTIONS: Promotion[] = [
  {
    id: 'promo-001',
    name: 'Spring Into Savings',
    description: '15% off all dog and cat food during our Spring sale event!',
    type: 'percentage',
    value: 15,
    conditions: { minPurchase: 50 },
    applicableProducts: [],
    applicableCategories: ['food'],
    startDate: '2026-03-15',
    endDate: '2026-04-15',
    isActive: true,
    usageCount: 0,
    code: 'SPRING15',
  },
  {
    id: 'promo-002',
    name: 'New Member Welcome',
    description: '$10 off your first purchase over $40 as a new Paw Member!',
    type: 'fixed',
    value: 10,
    conditions: { minPurchase: 40, firstPurchaseOnly: true },
    applicableProducts: [],
    applicableCategories: [],
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
    usageCount: 34,
    code: 'WELCOME10',
  },
  {
    id: 'promo-003',
    name: 'AutoShip Savings',
    description: 'Save 10% on every AutoShip order — set it and forget it!',
    type: 'percentage',
    value: 10,
    conditions: { autoShipOnly: true },
    applicableProducts: [],
    applicableCategories: [],
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
    usageCount: 156,
  },
  {
    id: 'promo-004',
    name: 'Double Points Weekend',
    description: 'Earn 2x loyalty points on all purchases this weekend!',
    type: 'loyalty-multiplier',
    value: 2,
    conditions: {},
    applicableProducts: [],
    applicableCategories: [],
    startDate: '2026-03-15',
    endDate: '2026-03-17',
    isActive: true,
    usageCount: 0,
  },
];

// ---- SUPPLIERS ----
export const SEED_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-fromm',
    name: 'Fromm Family Foods',
    contactName: 'Regional Sales Rep',
    email: 'orders@frommfamily.com',
    phone: '(800) 325-6331',
    address: {
      street: '123 Supplier St',
      city: 'Mequon',
      province: 'WI',
      postalCode: '53092',
      country: 'US',
    },
    products: ['prod-001', 'prod-003', 'prod-006', 'prod-009'],
    leadTimeDays: 7,
    minimumOrder: 500,
    paymentTerms: 'Net 30',
    notes: 'Primary food supplier. Very reliable.',
    isActive: true,
  },
  {
    id: 'sup-petcurean',
    name: 'Petcurean (GO! & NOW FRESH)',
    contactName: 'Ontario Sales',
    email: 'orders@petcurean.com',
    phone: '(866) 864-6112',
    address: {
      street: '456 Supplier Ave',
      city: 'Chilliwack',
      province: 'BC',
      postalCode: 'V2R 5G5',
      country: 'CA',
    },
    products: ['prod-002', 'prod-008', 'prod-019'],
    leadTimeDays: 5,
    minimumOrder: 400,
    paymentTerms: 'Net 30',
    notes: 'Canadian company. GO! and NOW FRESH brands.',
    isActive: true,
  },
  {
    id: 'sup-champion',
    name: 'Champion Petfoods (ACANA & ORIJEN)',
    contactName: 'Eastern Canada Rep',
    email: 'orders@championpetfoods.com',
    phone: '(780) 886-6658',
    address: {
      street: '789 Champion Way',
      city: 'Edmonton',
      province: 'AB',
      postalCode: 'T6H 4M6',
      country: 'CA',
    },
    products: ['prod-004', 'prod-010'],
    leadTimeDays: 6,
    minimumOrder: 600,
    paymentTerms: 'Net 30',
    notes: 'Premium brand. High demand products.',
    isActive: true,
  },
];

// ---- RECENT ORDERS (for POS history) ----
export const SEED_ORDERS: Order[] = [
  {
    id: 'ord-001',
    orderNumber: 'FPF-2026-0001',
    customerId: 'cust-002',
    customerName: 'Mike Thompson',
    items: [
      { id: 'oi-001', productId: 'prod-001', productName: 'Fromm Gold Adult Dog Food', sku: 'FRM-GLD-ADT-15', quantity: 1, unitPrice: 79.99, discount: 12.00, totalPrice: 67.99, isAutoShip: true },
      { id: 'oi-002', productId: 'prod-006', productName: 'Fromm Tenderollies Chick-a-Rollie', sku: 'FRM-TEND-CHK-8', quantity: 2, unitPrice: 12.99, discount: 0, totalPrice: 25.98, isAutoShip: false },
      { id: 'oi-003', productId: 'prod-005', productName: 'GREENIES Original Dental Treats', sku: 'GRN-DT-REG-27', quantity: 1, unitPrice: 34.99, discount: 0, totalPrice: 34.99, isAutoShip: false },
    ],
    subtotal: 128.96,
    taxAmount: 16.76,
    discountAmount: 12.00,
    totalAmount: 145.72,
    paymentMethod: 'debit',
    paymentStatus: 'completed',
    orderStatus: 'completed',
    loyaltyPointsEarned: 437,
    loyaltyPointsRedeemed: 0,
    giftCardAmountUsed: 0,
    notes: 'Regular autoship + extras',
    employeeId: 'emp-002',
    employeeName: 'Jamie Reynolds',
    channel: 'pos',
    createdAt: '2026-03-13T10:15:00Z',
    completedAt: '2026-03-13T10:18:00Z',
  },
  {
    id: 'ord-002',
    orderNumber: 'FPF-2026-0002',
    customerId: 'cust-001',
    customerName: 'Sarah Mitchell',
    items: [
      { id: 'oi-004', productId: 'prod-004', productName: 'ACANA Highest Protein Meadowland', sku: 'ACN-HP-MDL-11', quantity: 1, unitPrice: 89.99, discount: 9.00, totalPrice: 80.99, isAutoShip: true },
      { id: 'oi-005', productId: 'prod-010', productName: 'ORIJEN Cat & Kitten', sku: 'ORJ-CK-5', quantity: 1, unitPrice: 64.99, discount: 0, totalPrice: 64.99, isAutoShip: false },
      { id: 'oi-006', productId: 'prod-013', productName: 'Interactive Feather Wand Toy', sku: 'FE-TOY-FW-01', quantity: 1, unitPrice: 11.99, discount: 0, totalPrice: 11.99, isAutoShip: false },
    ],
    subtotal: 157.97,
    taxAmount: 20.54,
    discountAmount: 9.00,
    totalAmount: 178.51,
    paymentMethod: 'credit',
    paymentStatus: 'completed',
    orderStatus: 'completed',
    loyaltyPointsEarned: 357,
    loyaltyPointsRedeemed: 0,
    giftCardAmountUsed: 0,
    notes: '',
    employeeId: 'emp-003',
    employeeName: 'Alex Nguyen',
    channel: 'pos',
    createdAt: '2026-03-13T11:30:00Z',
    completedAt: '2026-03-13T11:34:00Z',
  },
  {
    id: 'ord-003',
    orderNumber: 'FPF-2026-0003',
    customerId: 'cust-004',
    customerName: 'David LaRose',
    items: [
      { id: 'oi-007', productId: 'prod-002', productName: 'GO! Solutions Carnivore Chicken, Turkey + Duck', sku: 'GO-CARN-CTD-12', quantity: 1, unitPrice: 74.99, discount: 0, totalPrice: 74.99, isAutoShip: false },
    ],
    subtotal: 74.99,
    taxAmount: 9.75,
    discountAmount: 0,
    totalAmount: 84.74,
    paymentMethod: 'cash',
    paymentStatus: 'completed',
    orderStatus: 'completed',
    loyaltyPointsEarned: 75,
    loyaltyPointsRedeemed: 0,
    giftCardAmountUsed: 0,
    notes: 'Paid with cash',
    employeeId: 'emp-004',
    employeeName: 'Morgan Beaulieu',
    channel: 'pos',
    createdAt: '2026-03-13T14:05:00Z',
    completedAt: '2026-03-13T14:07:00Z',
  },
];
